### ISSUE TITLE
check_admins.ps1: Bad --usernames params handling in some cases

### ISSUE THREAD

**Issue by dalibor-aleksic-atomia** [atomia/atomia-nagios-plugins#7]
Parameter `$usernames` is marked as array:
```
param (
    [string]$domain = $null,
    [string]$local = $null,
    [string[]]$usernames  # <= array
)
```
Depending of way how this paramater is specified, it will be handled diffrently:

#### Case without quotes `--usernames ATOMIA\Administrator,ATOMIA\User`
`$username` will be parsed as `[ "Atomia\Administrator", "ATOMIA\User" ]` as expected.

#### Case without quotes + username with spaces: `--usernames ATOMIA\Administrator,ATOMIA\Some User`

`$username` will be parsed as `[ "Atomia\Administrator", "ATOMIA\Some" ]`.

Problem: `ATOMIA\Some User` will not be parsed correctly.

#### Case with quotes (+username with spaces): `--usernames "ATOMIA\Administrator,ATOMIA\Some User"`

`$username` will be parsed as `[ "ATOMIA\Administrator,ATOMIA\Some User" ]` as array with one element.

Problem: Everything will be treated as single parameter / one element. This will cause issues for:
```
if( $usernames -contains $item)
```
to properly match accounts.

**Comment by NVitanovic** [comment]
In order to achieve what you seek you should provide usernames in format:
```
--usernames "username1","username2","username3"
```
or
```
--usernames 'username1','username2','username3'
```

In Nagios when specifying one argument you should quote the whole string with double quotes and individual usernames with single quotes:
```
--usernames "'username1','username2','username3'"
```
or
```
--usernames '"username1","username2","username3"'
```

**Comment by NVitanovic** [comment]
Thanks for the pull request @dalibor-aleksic-atomia 😎
